### ISSUE TITLE
Finish up the work on the API

### ISSUE THREAD

**Issue by Loriko** [Loriko/project_jetson#108]
1. Create Get Requests for API using already implemented queries and/or new queries. 
2. Update API Documentation. 
3. API Testing (unit, postman). 
4. Auto calculate hourly and daily averages upon specific queries/scenarios. (big task, may take me a full sprint***)

**Comment by mrama030** [comment]
Don't think its possible to finish api that quick, I have planned sprints 7 - 11 already with issues assigned to me if you want to take a look.

**Comment by Loriko** [comment]
Closed for being too global and undescriptive
