### ISSUE TITLE
Constantly fulfill database schema changes from other team members

### ISSUE THREAD

**Issue by mrama030** [Loriko/project_jetson#17]

**Comment by mrama030** [comment]
Required changes:
1. Combine "date" and "time" columns (in database) into a DATETIME column
2. Ensure all required Web API classes are tables when specified.

Do not close this issue right away. Just comment requests and fulfilled requests here.

**Comment by Loriko** [comment]
I'd suggest using separate issues for each request. I think it'd be better if each issue was resolvable instead of permanently ongoing so that the issue list was easier to navigate
