### ISSUE TITLE
Implement basic Web API testing suite - In Progress

### ISSUE THREAD

**Issue by Loriko** [Loriko/project_jetson#72]
A testing suite automating calls to the API should be implemented.
Postman and Unit Tests (NUnit 3) should be used.

**Comment by mrama030** [comment]
Persist has 5 postman tests uploaded. The other API actions will be implemented + tested as we go.

**Comment by mrama030** [comment]
Unit Tests Now In Progress, will still need to do some for DataMessageService class and maybe some other API classes. View Commit #102

**Comment by mrama030** [comment]
Postman tests and unit tests sufficient.
