### ISSUE TITLE
Update Database Query Service to make use of the new table/columns names

### ISSUE THREAD

**Issue by Loriko** [Loriko/project_jetson#74]
Database query service references the column/table names when it executes a query. These need to be updated according to the naming changes done in #73.

**Comment by Loriko** [comment]
Removed from sprint 6 because of other tasks taking more time than scheduled

**Comment by mrama030** [comment]
#Mohamed_Sprint_7_API
Database schema had to be modified as well.
- Still need to update the actual queries but the database models have been updated.
