### ISSUE TITLE
Create API methods to support the "View last updated people count for a camera" use case

### ISSUE THREAD

**Issue by Loriko** [Loriko/project_jetson#88]
The API will support a get request that for a given camera id, returns the last per second stat recorded for that camera id.

The API should support GET requests that for a given location_id, returns information on every camera available at that location. This information should include the camera_id of each camera.

Create a get request that takes a username and returns for that username a list of all locations available to that user (this information should include the location_id).
Right now, we don't have any restrictions on which user can access which location so every location that are linked with a least 1 camera should be returned.

**Comment by mrama030** [comment]
Will double check if this is done already and update code if needed.

**Comment by mrama030** [comment]
Complete, update all API's HTTP actions to support API Key authentication.
